volumes:
  cowrie-var:
    driver: local
  web-servie-log:
    driver: local
  rtsp-resource:
    driver: local

services:
  cowrie_service:
    image: cowrie/cowrie:latest
    container_name: cowrie-services
    restart: unless-stopped
    env_file: ./.env
    environment:
      - COWRIE_LOCAL_PORT=$COWRIE_LOCAL_PORT
      - COWRIE_DOCKER_PORT=$COWRIE_DOCKER_PORT
    ports:
      - ${COWRIE_LOCAL_PORT}:${COWRIE_DOCKER_PORT}
    volumes:
      - cowrie-var:/cowrie/cowrie-git/var
  mysql_service:
    image: mysql:8.0.28
    container_name: mysql_service
    cap_add:
      - SYS_NICE
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD 
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - "3306:3306"
    volumes:
      - ./initialize.sql:/docker-entrypoint-initdb.d/initialize.sql
  web_service:
    container_name: web_service
    depends_on:
      - mysql_service
    build: ./webservices
    restart: unless-stopped
    env_file: ./.env
    environment:
      - DB_HOST=mysql_service
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
      - SESSION_SECRET=$SESSION_SECRET
      - JWT_SECRET=$JWT_SECRET
      - ADMIN_PATH=$ADMIN_PATH
      - DEFAULT_ADMIN_NAME=$DEFAULT_ADMIN_NAME
      - DEFAULT_ADMIN_PASSWORD=$DEFAULT_ADMIN_PASSWORD
      - TELEGRAM_CHAT_ID=$TELEGRAM_CHAT_ID
      - TELEGRAM_TOKEN=$TELEGRAM_TOKEN
      - EMAIL_ADDRESS=$EMAIL_ADDRESS
      - EMAIL_PASSWORD=$EMAIL_PASSWORD
      - EMAIL_ADDRESS_TARGET=$EMAIL_ADDRESS_TARGET
      - EMAIL_SERVICE=$EMAIL_SERVICE
      - EMAIL_HOST=$EMAIL_HOST
    ports:
      - "3000:3000"
    volumes:
      - web-servie-log:/app/webservices/logs
    stdin_open: true
  dahua_web:
    container_name: dahua_web
    build: 
      context: ./webservices
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - CAMERA_TYPE=dahua
      - DAHUA_PORT=3000
    ports:
      - "3002:3000"
    stdin_open: true
    tty: true
  hikvision_web:
    container_name: hikvision_web
    build: 
      context: ./webservices
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - CAMERA_TYPE=hikvision
      - HIKVISION_PORT=3000
    ports:
      - "3001:3000"
    stdin_open: true
    tty: true
  rtsp_service:
    build: ./rtspservices
    container_name: rtsp_service
    restart: unless-stopped
    environment:
      - RTSP_LOCAL_PORT=554
      - RTSP_DOCKER_PORT=8554
      - MTX_PROTOCOLS=tcp
    ports:
      - "554:554"
    volumes:
      - ./videos:/app/rtsp/videos
      - rtsp-resource:/app/rtsp
  