volumes:
  cowrie-var:
    driver: local
  web-servie-log:
    driver: local
  rtsp-resource:
    driver: local

services:
  cowrie_service:
    image: cowrie/cowrie:latest
    container_name: cowrie-services
    restart: unless-stopped
    env_file: ./.env
    environment:
      - COWRIE_LOCAL_PORT=$COWRIE_LOCAL_PORT
      - COWRIE_DOCKER_PORT=$COWRIE_DOCKER_PORT
    ports:
      - ${COWRIE_LOCAL_PORT}:${COWRIE_DOCKER_PORT}
    volumes:
      - cowrie-var:/cowrie/cowrie-git/var
  mysql_service:
    image: mysql:8.0.28
    container_name: mysql_service
    cap_add:
      - SYS_NICE
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD 
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - "3306:3306"
    volumes:
      - ./initialize.sql:/docker-entrypoint-initdb.d/initialize.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
  web_service:
    container_name: web_service
    build: 
      context: ./webservices
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - DB_HOST=mysql_service
      - DB_USER=root
      - DB_PASSWORD=123456
      - DB_NAME=sweetcam
      - DB_PORT=3306
    stdin_open: true
    tty: true
    depends_on:
      mysql_service:
        condition: service_healthy

  rtsp_streaming_service:
    build:
      context: ./rtspservices
      dockerfile: Dockerfile
    container_name: rtsp_streaming_service
    restart: unless-stopped
    cap_add:
      - NET_BIND_SERVICE
    ports:
      - "554:554"
      - "8002:8002"
      - "8003:8003"
      - "8004:8004"
      - "8005:8005"
  axis_service:
    build:
      context: ./webservices
      dockerfile: Dockerfile
    container_name: axis_service
    restart: unless-stopped
    environment:
      - BRAND=axis
      - PORT=10000
    ports:
      - "10000:10000"
    depends_on:
      mysql_service:
        condition: service_healthy

  dahua_service:
    build:
      context: ./webservices
      dockerfile: Dockerfile
    container_name: dahua_service
    restart: unless-stopped
    environment:
      - BRAND=dahua
      - PORT=37777
    ports:
      - "37777:37777"
    depends_on:
      mysql_service:
        condition: service_healthy

  hikvision_service:
    build:
      context: ./webservices
      dockerfile: Dockerfile
    container_name: hikvision_service
    restart: unless-stopped
    environment:
      - BRAND=hikvision
      - PORT=80
    ports:
      - "80:80"
    depends_on:
      mysql_service:
        condition: service_healthy

  mobotix_service:
    build:
      context: ./webservices
      dockerfile: Dockerfile
    container_name: mobotix_service
    restart: unless-stopped
    environment:
      - BRAND=mobotix
      - PORT=443
    ports:
      - "443:443"
    depends_on:
      mysql_service:
        condition: service_healthy

  reolink_service:
    build:
      context: ./webservices
      dockerfile: Dockerfile
    container_name: reolink_service
    restart: unless-stopped
    environment:
      - BRAND=reolink
      - PORT=8081
    ports:
      - "8081:8081"
    depends_on:
      mysql_service:
        condition: service_healthy

  vstarcam_service:
    build:
      context: ./webservices
      dockerfile: Dockerfile
    container_name: vstarcam_service
    restart: unless-stopped
    environment:
      - BRAND=vstarcam
      - PORT=81
    ports:
      - "81:81"
    depends_on:
      mysql_service:
        condition: service_healthy